# Generated by Django 4.0 on 2025-08-22 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户')),
                ('ipv6_address', models.CharField(max_length=45, unique=True, verbose_name='IPv6地址')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC地址')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('create_time', models.DateTimeField(verbose_name='注册时间')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户')),
                ('building', models.SmallIntegerField(choices=[(1, '1栋'), (2, '2栋'), (3, '3栋'), (4, '4栋'), (5, '5栋'), (6, '6栋'), (7, '7栋'), (8, '8栋'), (9, '9栋'), (10, '10栋'), (11, '11栋'), (12, '12栋'), (13, '13栋'), (14, '14栋'), (15, '15栋'), (16, '16栋'), (17, '17栋'), (18, '18栋'), (19, '19栋'), (20, '20栋'), (21, '21栋'), (22, '22栋'), (23, '23栋'), (24, '24栋'), (25, '25栋'), (26, '26栋'), (27, '27栋'), (28, '28栋'), (29, '29栋'), (30, '30栋')], default=1, verbose_name='楼栋')),
                ('business_type', models.SmallIntegerField(choices=[(1, '物联网设备01'), (2, '物联网设备02'), (3, '物联网设备03'), (4, '物联网设备04'), (5, '物联网设备05')], default=1, verbose_name='业务类型')),
                ('duid', models.CharField(blank=True, max_length=64, null=True, verbose_name='DUID')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='设备MAC')),
                ('status', models.SmallIntegerField(choices=[(0, '不同意'), (1, '同意'), (2, '审批中')], default=2, verbose_name='状态')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户')),
                ('create_time', models.DateTimeField(verbose_name='审批时间')),
                ('building', models.SmallIntegerField(choices=[(1, '1栋'), (2, '2栋'), (3, '3栋'), (4, '4栋'), (5, '5栋'), (6, '6栋'), (7, '7栋'), (8, '8栋'), (9, '9栋'), (10, '10栋'), (11, '11栋'), (12, '12栋'), (13, '13栋'), (14, '14栋'), (15, '15栋'), (16, '16栋'), (17, '17栋'), (18, '18栋'), (19, '19栋'), (20, '20栋'), (21, '21栋'), (22, '22栋'), (23, '23栋'), (24, '24栋'), (25, '25栋'), (26, '26栋'), (27, '27栋'), (28, '28栋'), (29, '29栋'), (30, '30栋')], default=1, verbose_name='楼栋')),
                ('business_type', models.SmallIntegerField(choices=[(1, '物联网设备01'), (2, '物联网设备02'), (3, '物联网设备03'), (4, '物联网设备04'), (5, '物联网设备05')], default=1, verbose_name='业务类型')),
                ('duid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='DUID')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='设备MAC')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门')),
            ],
        ),
    ]
