# Generated by Django 4.0 on 2025-08-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prettynum',
            name='api_response',
            field=models.TextField(blank=True, null=True, verbose_name='API响应'),
        ),
        migrations.AddField(
            model_name='prettynum',
            name='last_send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后发送时间'),
        ),
        migrations.AddField(
            model_name='prettynum',
            name='next_retry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间'),
        ),
        migrations.AddField(
            model_name='prettynum',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='prettynum',
            name='send_status',
            field=models.CharField(choices=[('pending', '待发送'), ('success', '发送成功'), ('failed', '发送失败'), ('retrying', '重试中')], default='pending', max_length=10, verbose_name='发送状态'),
        ),
    ]
