# Generated by Django 4.0 on 2025-08-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_prettynum_api_response_prettynum_last_send_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='send_status',
            field=models.CharField(choices=[('pending', '待发送'), ('bound', '绑定成功'), ('failed', '发送失败'), ('bind_failed', '绑定失败'), ('retrying', '重试中')], default='pending', max_length=15, verbose_name='状态'),
        ),
    ]
