# Generated by Django 4.0 on 2025-08-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_prettynum_send_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prettynum',
            name='building',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1栋'), (2, '2栋'), (3, '3栋'), (4, '4栋'), (5, '5栋'), (6, '6栋'), (7, '7栋'), (8, '8栋'), (9, '9栋'), (10, '10栋'), (11, '11栋'), (12, '12栋'), (13, '13栋'), (14, '14栋'), (15, '15栋'), (16, '16栋'), (17, '17栋'), (18, '18栋'), (19, '19栋'), (20, '20栋'), (21, '21栋'), (22, '22栋'), (23, '23栋'), (24, '24栋'), (25, '25栋'), (26, '26栋'), (27, '27栋'), (28, '28栋'), (29, '29栋'), (30, '30栋')], default=1, null=True, verbose_name='楼栋'),
        ),
        migrations.AddField(
            model_name='prettynum',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='send_status',
            field=models.CharField(choices=[('pending', '待发送'), ('bound', '绑定成功'), ('failed', '发送失败'), ('bind_failed', '绑定失败'), ('retrying', '重试中')], default='pending', max_length=15, verbose_name='绑定状态'),
        ),
    ]
