# Generated by Django 4.0 on 2025-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_prettynum_building_prettynum_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('offline', '已下线')], default='online', max_length=10, verbose_name='设备状态'),
        ),
    ]
