# Generated by Django 4.0 on 2025-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='注册时间'),
            preserve_default=False,
        ),
    ]
