# Generated by Django 4.0 on 2025-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPv6Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=32, verbose_name='管理员名')),
                ('vlan_id', models.IntegerField(help_text='VLAN范围在2-4094', verbose_name='业务VLAN')),
                ('gateway', models.CharField(help_text='例如：240C:C901:A:A::1/64', max_length=64, verbose_name='业务网关')),
                ('dhcp_relay', models.CharField(help_text='例如：2001:250:6c00:3:8241:26ff:fe5f:ee2e', max_length=64, verbose_name='DHCP服务器中继地址')),
                ('send_status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=10, verbose_name='发送状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_response', models.TextField(blank=True, null=True, verbose_name='API响应')),
            ],
        ),
    ]
