# Generated by Django 4.0 on 2025-08-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_userinfo_account_remove_userinfo_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='register_time',
            field=models.DateTimeField(verbose_name='注册时间'),
        ),
    ]
