# Generated by Django 4.0 on 2025-08-21 08:59

from django.db import migrations
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_userinfo_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(verbose_name='注册时间', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
